### ISSUE TITLE
Randomly assign computer choice to computer variable

### ISSUE THREAD

**Issue by graceoreilly** [SchoolOfCode/week-2-hackathon-rock-paper-scissors-bc18-team9#11]
- Create an array with computer's choices
- Use random number to select an index between the choices

**Comment by fergus-g** [comment]
When working on the ticket, we followed this flow
// create way to randomly choose computer input
// create array of choices
// randomly choose this when the game runs
// assign to computerInput

**Comment by fergus-g** [comment]
As we worked on this issue, we identified that our pre-exisiting variable could be repurposed to resolve this ticket
