### ISSUE TITLE
Create logic/ mechanism to compare user input and computer input

### ISSUE THREAD

**Issue by graceoreilly** [SchoolOfCode/week-2-hackathon-rock-paper-scissors-bc18-team9#12]
- create an if block

- [ ] Rock	Paper
- [ ] Rock	Scissor
- [ ] Paper	Rock
- [ ] Paper	Scissor
- [ ] Scissor	Rock
- [ ] Scissor	Paper

**Comment by Maddy-bee** [comment]
// create an if block that compares the userInput and the compputerInput
// 
//  if URock CPaper then C wins DONE

//  if URock CScissors then U wins DONE

// if  UPaper CRock then U wins DONE

//  if UPaper CScissors then C wins DONE

//  If UScissors C Rock then C wins DONE

//  If UScissors C Paper then U wins DONE

// If U === C then tie 

// if userInput doesn't equally of your approved choices then a message will inform them 

// e.g. if userInput === "rock" && computerInput === "paper" 
// alert ("You have won")

// main.js:12 Uncaught ReferenceError: computerInput is not defined
//at main.js:12:29

// removed curly brackets on line 5 and 10 as computer was block scoped and we wanted it to be globally scoped.

// tested first if statement and troubleshooted until successful 


// we spotted a bug in variable and added to line 7 gameChoices[Math.floor(Math.random()*gameChoices.length)]
